export const BUILT_IN_COMPONENT_SCHEMAS = [
  { type: 'HeroPanel', allowedZones: ['root'], requiredProps: ['title'] },
  { type: 'RichTextBlock', allowedZones: ['root'], requiredProps: [] },
  { type: 'VariantSelector', allowedZones: ['root'], requiredProps: [] },
  { type: 'ProductSpotlight', allowedZones: ['root'], requiredProps: [] },
  { type: 'CheckoutGrid', allowedZones: ['root'], requiredProps: [] },
  { type: 'ShippingAddressForm', allowedZones: ['root'], requiredProps: [] },
  { type: 'PaymentEntryForm', allowedZones: ['root'], requiredProps: [] },
  { type: 'OrderSummaryCard', allowedZones: ['root'], requiredProps: [] },
  { type: 'CountdownTimer', allowedZones: ['root'], requiredProps: [] },
  { type: 'ReviewList', allowedZones: ['root'], requiredProps: [] },
  { type: 'FaqAccordion', allowedZones: ['root'], requiredProps: [] },
  { type: 'PageFooter', allowedZones: ['root'], requiredProps: [] },
  { type: 'ColumnLayout', allowedZones: ['root'], requiredProps: [] },
  { type: 'ImageBlock', allowedZones: ['root'], requiredProps: [] },
  { type: 'UrgencyProofBar', allowedZones: ['root'], requiredProps: [] },
  { type: 'TrustBadgeRow', allowedZones: ['root'], requiredProps: [] },
  { type: 'PriceComparisonColumns', allowedZones: ['root'], requiredProps: [] },
  { type: 'ReferralCard', allowedZones: ['root'], requiredProps: [] },
];
