// React-free list of every core Puck component type key (mirrors config.tsx components),
// so server-only paths can resolve the registered component set without importing the
// React block bundle. Plugin keys are added at runtime from builderExtensions.
export const CORE_COMPONENT_KEYS = [
  'HeroPanel',
  'PayPalExpressButton',
  'CountdownTimer',
  'ReviewList',
  'RichTextBlock',
  'CallToActionBanner',
  'PageFooter',
  'ImageTextSplit',
  'EndorsementPanel',
  'ProductSpotlight',
  'HowToSteps',
  'FaqAccordion',
  'StickyCheckoutBar',
  'CheckoutGrid',
  'ShippingAddressForm',
  'PaymentEntryForm',
  'OrderSummaryCard',
  'CouponField',
  'OrderDetailPanel',
  'UpsellAddButton',
  'OrderTrackingPanel',
  'PromoBanner',
  'StockMeter',
  'CheckoutHeader',
  'SavingsBadge',
  'VariantSelector',
  'BenefitList',
  'ImageBlock',
  'StandaloneShippingForm',
  'StickyPageHeader',
  'ColumnLayout',
  'UpsellHeader',
  'NoticeBar',
  'StoreHeader',
  'HeroCarousel',
  'CategoryTiles',
  'ProductGrid',
  'FeatureIconRow',
  'MediaGrid',
  'SocialShareRow',
  'CodeSnippet',
  'StepProgress',
  'UrgencyProofBar',
  'TrustBadgeRow',
  'PriceComparisonColumns',
  'ReferralCard',
] as const;
